name: Build Typst document (CI)
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - uses: typst-community/setup-typst@v3
        with:
          version: latest

      - name: Compile Typst to PDF
        uses: mkpoli/compile-typst-action@main
        with:
          source_paths: "examples/exam-001.typ examples/exam-002.typ examples/exam-003.typ examples/exam-005.typ examples/exam-localization.typ examples/exam-minimal.typ"
          output_paths: 'examples/exam-001.ci.pdf examples/exam-002.ci.pdf examples/exam-003.ci.pdf examples/exam-005.ci.pdf examples/exam-localization.ci.pdf examples/exam-minimal.ci.pdf'
          root_path: '.'

      - name: Check existence of output file
        run: |
          test -e "examples/exam-001.ci.pdf"
          test -e "examples/exam-002.ci.pdf"
          test -e "examples/exam-003.ci.pdf"
          test -e "examples/exam-004.ci.pdf"
          test -e "examples/exam-localization.ci.pdf"
          test -e "examples/exam-minimal.ci.pdf"


      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: examples
          path: ./examples/*.ci.pdf
