name: Build Typst document (CI)
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    working-directory: ./examples

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Sample directory
      #   run: |
      #     cd ./examples/

      - name: Typst
        uses: lvignoli/typst-action@main   
        with:
          source_file: |
            exam-003.typ
              
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            exam-001.typ
            exam-002.typ
            exam-minimal.typ

      # - name: Upload PDF file
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: PDF
      #     path: *.pdf

      # - name: Get current date
      #   id: date
      #   run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   if: github.ref_type == 'tag'
      #   with:
      #     name: "${{ github.ref_name }} — ${{ env.DATE }}"
      #     files: main.pdf